### ISSUE TITLE
Potential error on p124

### ISSUE THREAD

**Issue by littleMaster2002** [mrpsharp/physics-PreU#38]
The equation below the line beginning "Now we are using many particles we can make the assumption that a particle
is equally likely..." should have z as the subscript letter for the third term.

**Comment by littleMaster2002** [comment]
(Also, a potential typo on p126 - "termperature")

**Comment by littleMaster2002** [comment]
(Also, a potential typo on p28 - "the time take")

**Comment by mrpsharp** [comment]
Fixed in v2.3.3
Thank you for the feedback.
